Maximum Value of an Arithmetic Expression

Parenthesize an arithmetic expression to maxi- mize its value.

Input. A string s=s0s1⋯s2n of length at most 29. Each symbol at an even position of s is a digit (that is, an integer from 0 to 9) while each symbol at an odd position is one of three operations from {+,−,∗}.

Output. The maximum value of the given arithmetic expression among all possible orders of applying arithmetic operations.

In [44]:
i = "5-8+7*4-8+9", 200

In [2]:
i[0]

'5-8+7*4-8+9'

In [3]:
def find_maximum_value(dataset):
    pass


In [4]:
import numpy as np
def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    A = np.zeros((len(numbers),len(numbers)), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    
    return 1 dataset[1] 2
find_maximum_value(i[0])

SyntaxError: invalid syntax (<ipython-input-4-dd119a2d74fd>, line 8)

In [5]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
    '/' : operator.truediv,  # use operator.div for Python 2
    '%' : operator.mod,
    '^' : operator.xor,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((len(numbers),len(numbers), 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    
#     return ops[dataset[5]](1,2)
    return operations

find_maximum_value(i[0])

['-', '+', '*', '-', '+']

In [6]:
A[:,:,1]

NameError: name 'A' is not defined

In [7]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
    '/' : operator.truediv,  # use operator.div for Python 2
    '%' : operator.mod,
    '^' : operator.xor,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    for i in range(0,6):
        for j in range(0,6):
            if j > i:
                A[i,j] = i+j
            
    
#     return ops[dataset[5]](1,2)
    return A

B = find_maximum_value(i[0])
print(B[:,:,0])

[[5 1 2 3 4 5]
 [0 8 3 4 5 6]
 [0 0 7 5 6 7]
 [0 0 0 4 7 8]
 [0 0 0 0 8 9]
 [0 0 0 0 0 9]]


In [8]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
    '/' : operator.truediv,  # use operator.div for Python 2
    '%' : operator.mod,
    '^' : operator.xor,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    for i in range(0,6):
        for j in range(0,6):
            k = 0
            if j > i:
                print(A[i,j-1, k],operations[i],A[i+1,j, k])
                A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k]) 
            
    
#     return ops[dataset[5]](1,2)
    return A

B = find_maximum_value(i[0])
print(B[:,:,0])

5 - 8
-3 - 0
-3 - 0
-3 - 0
-3 - 0
8 + 7
15 + 0
15 + 0
15 + 0
7 * 4
28 * 0
0 * 0
4 - 8
-4 - 0
8 + 9
[[ 5 -3 -3 -3 -3 -3]
 [ 0  8 15 15 15 15]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4 -4]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]


In [9]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
    '/' : operator.truediv,  # use operator.div for Python 2
    '%' : operator.mod,
    '^' : operator.xor,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.empty((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    for i in range(0,6):
        for j in range(0,6):
            k = 0
            if j > i:
                print(A[i,j-1, k],operations[i],A[i+1,j, k])
                A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k]) 
            
    
#     return ops[dataset[5]](1,2)
    return A

B = find_maximum_value(i[0])
print(B[:,:,0])

5 - 8
-3 - 3
-6 - 4
-10 - 5
-15 - 6
8 + 7
15 + 5
20 + 6
26 + 7
7 * 4
28 * 7
196 * 8
4 - 8
-4 - 9
8 + 9
[[   5   -3   -6  -10  -15  -21]
 [   0    8   15   20   26   33]
 [   0    0    7   28  196 1568]
 [   0    0    0    4   -4  -13]
 [   0    0    0    0    8   17]
 [   0    0    0    0    0    9]]


In [10]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
    '/' : operator.truediv,  # use operator.div for Python 2
    '%' : operator.mod,
    '^' : operator.xor,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    i = 0
    j = 1
    k = 0
    while j > i:
        print('yaaa')
        print(A[i,j-1, k],operations[i],A[i+1,j, k])
        A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k])
        i+=1
        j+=1
        if j == y:
            print("TASDOIASDJA",i,j)
            j = j-i +2
            i = j-1
            print(A[:,:,0])
        
            
    

    return A[:,:,0]

find_maximum_value(i[0])

yaaa
5 - 8
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0

yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0 

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0 

yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]

TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]

TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]

yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]

yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0

yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0 

yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  

yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 

KeyboardInterrupt: 

In [11]:
import math
import operator

def calc(a, b, op):
    print(a,b)
    ops = {
        '+' : operator.add,
        '-' : operator.sub,
        '*' : operator.mul,
        '/' : operator.truediv,  # use operator.div for Python 2
        '%' : operator.mod,
        '^' : operator.xor,
    }
    
    ops[op](a, b) 

#     if op == '+':
#         return a + b
#     elif op == '-':
#         return a - b
#     else:
#         return a * b


def MinAndMax(M, m, i, j, operators):

    min_value = math.inf
    max_value = -math.inf
    for k in range(i, j):
        a = calc(M[i][k], M[k+1][j], operators[k])
        b = calc(M[i][k], m[k+1][j], operators[k])
        c = calc(m[i][k], M[k+1][j], operators[k])
        d = calc(m[i][k], m[k+1][j], operators[k])
        min_value = min(min_value, a, b, c, d)
        max_value = max(max_value, a, b, c, d)
    return min_value, max_value


def get_maximum_value(dataset):
    
    operators, operands = [], []

    for i in dataset:
        if i in ['+', '-', '*']:
            operators.append(i)
        else:
            operands.append(int(i))
    

    
    operations = [num for num in dataset if not num.isnumeric()]
    operands = operations

    n = len(operands)
    m = [[None for x in range(n)] for x in range(n)]
    M = [[None for x in range(n)] for x in range(n)]

    for i in range(n):
        m[i][i] = operands[i]
        M[i][i] = operands[i]

    for s in range(1, n):
        for i in range(0, n-s):
            j = i + s
            m[i][j], M[i][j] = MinAndMax(M, m, i, j, operators)

    return M[0][n-1]

In [12]:
get_maximum_value(i[0])

- +


TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [17]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    i = 0
    j = 1
    k = 0
    while j > i:
        print('yaaa')
        print(A[i,j-1, k],operations[i],A[i+1,j, k])
        A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k])
        i+=1
        j+=1
        if j == y:
            print("TASDOIASDJA",i,j)
            j = j-i + 1
            i = j-1
            print(A[:,:,0])
        
            
    

    return A[:,:,0]

B = find_maximum_value(i[0])

yaaa
5 - 8
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJ

4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15 

7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]


7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]


TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9

yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0

TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0

8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0

8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 [ 0  0  7 28  0  0]
 [ 0  0  0  4 -4  0]
 [ 0  0  0  0  8 17]
 [ 0  0  0  0  0  9]]
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
TASDOIASDJA 5 6
[[ 5 -3  0  0  0  0]
 [ 0  8 15  0  0  0]
 

KeyboardInterrupt: 

In [20]:
B[:,:,0]

array([[   5,   -3,   -6,  -10,  -15,  -21],
       [   0,    8,   15,   20,   26,   33],
       [   0,    0,    7,   28,  196, 1568],
       [   0,    0,    0,    4,   -4,  -13],
       [   0,    0,    0,    0,    8,   17],
       [   0,    0,    0,    0,    0,    9]])

In [36]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
    '/' : operator.truediv,  # use operator.div for Python 2
    '%' : operator.mod,
    '^' : operator.xor,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    i = 0
    j = 1
    k = 0
    q = 0
    while j > i:
        print('yaaa')
        print(A[i,j-1, k],operations[i],A[i+1,j, k])
        A[i,j, k] = q
        q+=1
#         A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k])
        i+=1
        j+=1
        if j == y:
            y -= 1
            print(f"x:{x}, y:{y}, j:{j}, i:{i}")
            j = j-i
            i = j+x-y-1
            
            print(A[:,:,0])
            
        
            
    

    return A[:,:,0]

find_maximum_value(i[0])

yaaa
5 - 8
yaaa
8 + 7
yaaa
7 * 4
yaaa
4 - 8
yaaa
8 + 9
x:6, y:5, j:6, i:5
[[5 0 0 0 0 0]
 [0 8 1 0 0 0]
 [0 0 7 2 0 0]
 [0 0 0 4 3 0]
 [0 0 0 0 8 4]
 [0 0 0 0 0 9]]


array([[5, 0, 0, 0, 0, 0],
       [0, 8, 1, 0, 0, 0],
       [0, 0, 7, 2, 0, 0],
       [0, 0, 0, 4, 3, 0],
       [0, 0, 0, 0, 8, 4],
       [0, 0, 0, 0, 0, 9]])

In [42]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
    '/' : operator.truediv,  # use operator.div for Python 2
    '%' : operator.mod,
    '^' : operator.xor,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    i = 0
    j = 1
    k = 0
    q = 0
    
    d = 1
    
    while d < y:
        j = d
        while j < y :
            print('yaaa')
#             print(A[i,j-1, k],operations[i],A[i+1,j, k])
            A[i,j, k] = q
            q+=1
#             A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k])
            i+=1
            j+=1
#             if j == y-1:
#                 print(f"x:{x}, y:{y}, j:{j}, i:{i}")
#                 j = j-i
#                 i = j+x-y-1
        i = 0
        d += 1
        j = d
        
            
    

    return A[:,:,0]

find_maximum_value(i[0])

yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa


array([[    5,    -3,   -18,   -61,     8, -2275],
       [    0,     8,    15,    43,   -69,  2283],
       [    0,     0,     7,    28,  -112,  2352],
       [    0,     0,     0,     4,    -4,   -21],
       [    0,     0,     0,     0,     8,    17],
       [    0,     0,     0,     0,     0,     9]])

In [49]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    i = 0
    j = 1
    k = 0
    q = 0
    
    d = 1
    
    while d < y:
        j = d
        while j < y :
            print('yaaa')
#             print(A[i,j-1, k],operations[i],A[i+1,j, k])
            A[i,j, k] = q
            q+=1
#             A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k])
            i+=1
            j+=1
#             if j == y-1:
#                 print(f"x:{x}, y:{y}, j:{j}, i:{i}")
#                 j = j-i
#                 i = j+x-y-1
        i = 0
        d += 1
        j = d
        
            
    

    return A[:,:,0]

find_maximum_value(i[0])

yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa


array([[ 5,  0,  5,  9, 12, 14],
       [ 0,  8,  1,  6, 10, 13],
       [ 0,  0,  7,  2,  7, 11],
       [ 0,  0,  0,  4,  3,  8],
       [ 0,  0,  0,  0,  8,  4],
       [ 0,  0,  0,  0,  0,  9]])

In [69]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    print(A[:,:,0])
    i = 0
    j = 1
    k = 0
    q = 0
    
    d = 1
    
    while d < y:
        j = d
        
        while j < y :
            
            print('yaaa')
#             A[i,j, k] = q
#             q+=1
            A[i,j, k] = ops[operations[i]](A[i,j-1,k], A[i+1,j,k])
#             A[i,j, 0] = max(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
#             A[i,j, 1] = min(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
            
    
            i+=1
            j+=1
        i = 0
        d += 1
        j = d
        
            
    

    return A[:,:,0]

B = find_maximum_value(i[0])

[[5 0 0 0 0 0]
 [0 8 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa


In [66]:
B[0,:]

array([    5,    -3,   -18,   -61,     8, -2275])

In [68]:
B

array([[    5,    -3,   -18,   -61,     8, -2275],
       [    0,     8,    15,    43,   -69,  2283],
       [    0,     0,     7,    28,  -112,  2352],
       [    0,     0,     0,     4,    -4,   -21],
       [    0,     0,     0,     0,     8,    17],
       [    0,     0,     0,     0,     0,     9]])

In [72]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    print(A[:,:,0])
    i = 0
    j = 1
    k = 0
    q = 0
    
    d = 1
    
    while d < y:
        j = d
        
        while j < y :
            
            print('yaaa')
#             A[i,j, k] = q
#             q+=1
            A[i,j, k] = ops[operations[i]](A[i,i,k], A[i+1,j,k])
#             A[i,j, 0] = max(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
#             A[i,j, 1] = min(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
            
    
            i+=1
            j+=1
        i = 0
        d += 1
        j = d
        
            
    

    return A[:,:,0]

find_maximum_value(i[0])

[[5 0 0 0 0 0]
 [0 8 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa
yaaa


array([[  5,  -3, -10, -31,  25,  88],
       [  0,   8,  15,  36, -20, -83],
       [  0,   0,   7,  28, -28, -91],
       [  0,   0,   0,   4,  -4, -13],
       [  0,   0,   0,   0,   8,  17],
       [  0,   0,   0,   0,   0,   9]])

In [86]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    print(A[:,:,0])
    i = 0
    j = 1
    k = 0
    q = 0
    
    d = 1
    
    while d < y:
        j = d
        
        while j < y :
            
            print('yaaa')
#             A[i,j, k] = q
#             q+=1
            print(f"A:{type(A)}, cart:{type((i,j))}")
            A[i,j, k] = max_at_pos(A=A, cart=(i,j))
#             A[i,j, 0] = max(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
#             A[i,j, 1] = min(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
            
    
            i+=1
            j+=1
        i = 0
        d += 1
        j = d
        
            
    

    return A[:,:,0]


def max_at_pos(A, cart):
    '''
    Input: Array, column, cartesion position
    Output: largest possible value (negative, and pos)
    
    Number of times needed to iterate = j-i
    '''
    i, j = cart
    Results = []
    k = 0
    
    for z in range(0,j-i):
        x = A[i+1+z,j,k] + A[i,z,k]
    
    return x

find_maximum_value(i[0])

[[5 0 0 0 0 0]
 [0 8 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>


array([[ 5, 13, 20, 24, 32, 41],
       [ 0,  8,  7, 12, 15, 21],
       [ 0,  0,  7,  4,  8, 16],
       [ 0,  0,  0,  4,  8,  9],
       [ 0,  0,  0,  0,  8,  9],
       [ 0,  0,  0,  0,  0,  9]])

In [95]:
import numpy as np
import operator

ops = {
    '+' : operator.add,
    '-' : operator.sub,
    '*' : operator.mul,
}

def find_maximum_value(dataset):
    numbers = [num for num in dataset if num.isnumeric()]
    x = y = len(numbers)
    operations = [num for num in dataset if not num.isnumeric()]
    A = np.zeros((x,y, 2), dtype=int)
    for i, num in enumerate(numbers):
        A[i,i] = num
    print(A[:,:,0])
    i = 0
    j = 1
    k = 0
    q = 0
    
    d = 1
    
    while d < y:
        j = d
        
        while j < y :
            
            print('yaaa')
#             A[i,j, k] = q
#             q+=1
            print(f"A:{type(A)}, cart:{type((i,j))}")
            A[i,j, k] = max_at_pos(A=A, cart=(i,j), op=ops[operations[i]])
#             A[i,j, 0] = max(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
#             A[i,j, 1] = min(ops[operations[i]](A[i,j-1,0], A[i+1,j,0]), ops[operations[i]](A[i,j-1,1], A[i+1,j,1]))
            
    
            i+=1
            j+=1
        i = 0
        d += 1
        j = d
        
            
    

    return A[:,:,0]


def max_at_pos(A, cart, op):
    '''
    Input: Array, column, cartesion position
    Output: largest possible value (negative, and pos)
    
    Number of times needed to iterate = j-i
    '''
    i, j = cart
    Results = []
    k = 0
    
    for z in range(0,j-i):
#         x = A[i+1+z,j,k] + A[i,z,k]
#         x = A[i+1+z,j,k] + A[i,z,k]
        print(op, A[i+1+z,j,k], A[i,z,k])
        x = op(A[i,z,k], A[i+1+z,j,k])
    
        Results.append(x)
    
    return max(Results)

find_maximum_value(i[0])

[[5 0 0 0 0 0]
 [0 8 0 0 0 0]
 [0 0 7 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function sub> 8 5
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function add> 7 0
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function mul> 4 0
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function sub> 8 0
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function add> 9 0
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function sub> 7 5
<built-in function sub> 7 -3
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function add> 0 0
<built-in function add> 4 8
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function mul> -8 0
<built-in function mul> 8 0
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in function sub> 9 0
<built-in function sub> 9 0
yaaa
A:<class 'numpy.ndarray'>, cart:<class 'tuple'>
<built-in fun

array([[ 5, -3, -2, -3,  6,  7],
       [ 0,  8,  7, 12, 15, 63],
       [ 0,  0,  7,  0,  0, 63],
       [ 0,  0,  0,  4, -8, -9],
       [ 0,  0,  0,  0,  8,  9],
       [ 0,  0,  0,  0,  0,  9]])